// AUTO-GENERATED by scripts/sync-researchmap.mjs.
// Source: https://researchmap.jp/amrmap (awards, research_projects).
// Do not edit manually except for fields preserved by the sync script
// (publications.highlight by DOI, grants.role by title, books.role by title).
// Run `node scripts/sync-researchmap.mjs` to regenerate.

export type Award = {
  year: number;
  title: string;
  org?: string;
  url?: string;
};

export const awards: Award[] = [
  {
    year: 2024,
    title: "第3回計算社会科学大会 大会優秀賞 — ネットワーク分析による日本美術作品の定量分析： 浮世絵の創造性の変化",
    org: "計算社会科学会",
  },
  {
    year: 2015,
    title: "公共財団法人みずほ学術振興財団「第 56 回懸賞論文」佳作賞 — 量的・質的金融緩和の「出口戦略」を考える",
  },
  {
    year: 2015,
    title: "白木賞(優秀卒業論文) — 債券の削減バランスを考慮した「質的・量的金融緩和」の出口戦略シミュレーション",
    org: "神戸大学",
  },
];

export type Grant = {
  period: string;
  title: string;
  role: string;
  funder: string;
  url?: string;
  grantNumber?: string;
};

export const grants: Grant[] = [
  {
    period: "2025-04 – 2029-03",
    title: "連携型ロイヤルティ・プログラム市場の二面性構造を考慮した代替・補完関係の解明",
    role: "分担",
    funder: "JSPS 基盤研究(B)",
    grantNumber: "25K00680",
  },
  {
    period: "2024-04 – 2027-03",
    title: "日本の研究の包括的な再考察：科学者学による研究ポートフォリオの分析",
    role: "代表",
    funder: "JSPS 若手研究",
    grantNumber: "24K16359",
  },
  {
    period: "2023-11 – 2027-03",
    title: "陰謀論への流入経路の特定と人々の傾倒を未然に防ぐフレームワークの開発",
    role: "分担",
    funder: "JST RISTEX SDGsの達成に向けた共創的研究開発プログラム",
    grantNumber: "JPMJRS23L4",
  },
  {
    period: "2022-08 – 2024-03",
    title: "日本における科学者学：大規模な研究者データ構築による郵送限定公募の効果分析",
    role: "代表",
    funder: "JSPS 研究活動スタート支援",
    grantNumber: "22K20159",
  },
  {
    period: "2021-04 – 2024-03",
    title: "消費者の移動行動を基点とした商圏内小売競争構造の動態的把握に関する研究",
    role: "分担",
    funder: "JSPS 基盤研究(B)",
    grantNumber: "21H00756",
  },
  {
    period: "2017-04 – 2020-03",
    title: "金融危機対応の経済分析：非線形DSGEモデルによる大きなショック下の金融政策分析",
    role: "代表",
    funder: "JSPS 特別研究員奨励費",
    grantNumber: "17J04922",
  },
];
