// AUTO-GENERATED by scripts/sync-researchmap.mjs.
// Source: https://researchmap.jp/amrmap (published_papers, books_etc).
// Do not edit manually except for fields preserved by the sync script
// (publications.highlight by DOI, grants.role by title, books.role by title).
// Run `node scripts/sync-researchmap.mjs` to regenerate.

export type Publication = {
  year: number;
  date?: string; // raw researchmap publication_date: YYYY | YYYY-MM | YYYY-MM-DD
  authors: string;
  title: string;
  venue: string;
  url?: string;
  type?: 'journal' | 'conference' | 'preprint' | 'chapter' | 'book';
  highlight?: boolean;
};

export const publications: Publication[] = [
  {
    year: 2026,
    date: "2026-08-18",
    authors: "Sakai, S., Kwak, H., An, J. & Matsui, A.",
    title: "Gendered cultural discourse in Japan across the prewar–postwar transition: evidence from historical word embeddings",
    venue: "EPJ Data Science",
    url: "https://doi.org/10.1140/epjds/s13688-026-00688-5",
    type: "journal",
  },
  {
    year: 2026,
    date: "2026-08-10",
    authors: "Matsui, A., Teramoto, T., Motohashi, E. & Tsurumi, H.",
    title: "Modeling user redemption behavior in complex digital incentive environment: an empirical study using large-scale transactional data",
    venue: "EPJ Data Science",
    url: "https://doi.org/10.1140/epjds/s13688-026-00687-6",
    type: "journal",
  },
  {
    year: 2026,
    date: "2026-05-25",
    authors: "Matsui, A.",
    title: "Cross-Platform and Cross-Lingual Dynamics of Wikipedia Sharing and Contribution",
    venue: "Proceedings of the International AAAI Conference on Web and Social Media",
    url: "https://doi.org/10.1609/icwsm.v20i1.42713",
    type: "journal",
  },
  {
    year: 2026,
    date: "2026-03-24",
    authors: "Honna, S. & Matsui, A.",
    title: "Disruptive transformation of artworks in master-disciple relationships: the case of Ukiyo-e artworks",
    venue: "EPJ Data Science",
    url: "https://doi.org/10.1140/epjds/s13688-026-00646-1",
    type: "journal",
    highlight: true,
  },
  {
    year: 2024,
    date: "2024-12",
    authors: "Matsui, A. & Ferrara, E.",
    title: "Word embedding for social sciences: an interdisciplinary survey",
    venue: "PeerJ Computer Science",
    url: "https://doi.org/10.7717/peerj-cs.2562",
    highlight: true,
  },
  {
    year: 2024,
    date: "2024-10-19",
    authors: "Nishikawa, M., Sakai, D. & Matsui, A.",
    title: "The impact of the internationalization of political science on publishing in two languages: the case of Japan, 1971–2023",
    venue: "Scientometrics",
    url: "https://doi.org/10.1007/s11192-024-05179-w",
    type: "journal",
  },
  {
    year: 2024,
    date: "2024-08-01",
    authors: "Salama, S., Matsui, A. & Kamihigashi, T.",
    title: "Extracting Official Agencies’ Communication Patterns During the COVID-19 Pandemic: A Text Mining Approach",
    venue: "Proceedings of the Third International Conference on Innovations in Computing Research (ICR’24)",
    url: "https://doi.org/10.1007/978-3-031-65522-7_1",
    type: "chapter",
  },
  {
    year: 2024,
    date: "2024-06",
    authors: "Matsui, A., Murayama, T. & Yoshida, M.",
    title: "Hater Is Not the Only Source of Toxic Communication Online, But Also Fan",
    venue: "ICWSM 2024 Workshop : The 5th International Workshop on Cyber Social Threats (CySoc 2024)",
    url: "https://doi.org/10.36190/2024.03",
    type: "conference",
  },
  {
    year: 2024,
    date: "2024-05-28",
    authors: "Matsui, A., Miyazaki, K. & Murayama, T.",
    title: "Throw Your Hat in the Ring (of Wikipedia): Exploring Urban-Rural Disparities in Local Politicians' Information Supply",
    venue: "Proceedings of the International AAAI Conference on Web and Social Media (ICWSM)",
    url: "https://doi.org/10.1609/icwsm.v18i1.31370",
    type: "conference",
    highlight: true,
  },
  {
    year: 2023,
    date: "2023-06-02",
    authors: "Murayama, T., Matsui, A., Miyazaki, K., et al.",
    title: "The Chance of Winning Election Impacts on Social Media Strategy",
    venue: "Proceedings of the International AAAI Conference on Web and Social Media (ICWSM)",
    url: "https://doi.org/10.1609/icwsm.v17i1.22178",
    type: "conference",
  },
  {
    year: 2023,
    date: "2023-04-30",
    authors: "Miyazaki, K., Murayama, T., Matsui, A., et al.",
    title: "Political Honeymoon Effect on Social Media: Characterizing Social Media Reaction to the Changes of Prime Minister in Japan",
    venue: "Proceedings of the 15th ACM Web Science Conference 2023",
    url: "https://doi.org/10.1145/3578503.3583594",
    type: "conference",
  },
  {
    year: 2023,
    date: "2023-03-29",
    authors: "Benjamin, D. M., Morstatter, F., Abbas, A. E., et al.",
    title: "Hybrid forecasting of geopolitical events <sup>†</sup>",
    venue: "AI Magazine",
    url: "https://doi.org/10.1002/aaai.12085",
    type: "journal",
  },
  {
    year: 2022,
    date: "2022-01",
    authors: "Matsui, A. & Moriwaki, D.",
    title: "Online-to-offline advertisements as field experiments",
    venue: "The Japanese Economic Review",
    url: "https://doi.org/10.1007/s42973-021-00101-y",
    type: "journal",
  },
  {
    year: 2021,
    date: "2021-11",
    authors: "Matsui, A., Ren, X. & Ferrara, E.",
    title: "Using Word Embedding to Reveal Monetary Policy Explanation Changes",
    venue: "Proceedings of the Third Workshop on Economics and Natural Language Processing",
    url: "https://doi.org/10.18653/v1/2021.econlp-1.8",
    type: "conference",
  },
  {
    year: 2021,
    date: "2021-09",
    authors: "Matsui, A., Chen, E., Wang, Y. & Ferrara, E.",
    title: "The impact of peer review on the contribution potential of scientific papers",
    venue: "Peerj",
    url: "https://doi.org/10.7717/peerj.11999",
  },
  {
    year: 2021,
    date: "2021",
    authors: "Moriwaki, D., Hayakawa, Y., Matsui, A., et al.",
    title: "A Real-World Implementation of Unbiased Lift-based Bidding System",
    venue: "Proceedings of the IEEE International Conference on Big Data (Big Data)",
    url: "https://doi.org/10.1109/BigData52589.2021.9671800",
    type: "conference",
  },
  {
    year: 2020,
    date: "2020-08-20",
    authors: "Matsui, A., Kobayashi, T., Moriwaki, D. & Ferrara, E.",
    title: "Detecting multi-timescale consumption patterns from receipt data: a non-negative tensor factorization approach",
    venue: "Journal of Computational Social Science",
    url: "https://doi.org/10.1007/s42001-020-00078-5",
    type: "journal",
  },
  {
    year: 2020,
    date: "2020-01",
    authors: "Matsui, A., Sapienza, A. & Ferrara, E.",
    title: "Does Streaming Esports Affect Players' Behavior and Performance?",
    venue: "Games and Culture",
    url: "https://doi.org/10.1177/1555412019838095",
    type: "journal",
  },
  {
    year: 2019,
    date: "2019",
    authors: "Morstatter, F., Galstyan, A., Satyukov, G., et al.",
    title: "SAGE: A Hybrid Geopolitical Event Forecasting System",
    venue: "Proceedings of the Twenty-Eighth International Joint Conference on Artificial Intelligence (IJCAI)",
    type: "conference",
  },
  {
    year: 2018,
    date: "2018",
    authors: "Deb, A., Majmundar, A., Seo, S., et al.",
    title: "Social Bots for Online Public Health Interventions",
    venue: "Proceedings of the IEEE/ACM International Conference on Advances in Social Networks Analysis and Mining (ASONAM)",
    type: "conference",
  },
];

export type Book = {
  year: number;
  date?: string;
  title: string;
  role: string;
  publisher: string;
  url?: string;
};

export const books: Book[] = [
  {
    year: 2025,
    date: "2025-07",
    title: "サイエンス・オブ・サイエンス",
    role: "Author",
    publisher: "森北出版",
  },
];
