// AUTO-GENERATED by scripts/sync-researchmap.mjs.
// Source: https://researchmap.jp/amrmap (academic_contribution).
// Do not edit manually except for fields preserved by the sync script
// (publications.highlight by DOI, grants.role by title, books.role by title).
// Run `node scripts/sync-researchmap.mjs` to regenerate.

export type Service = {
  year: number;
  date?: string; // from_event_date: YYYY | YYYY-MM | YYYY-MM-DD
  endDate?: string; // to_event_date, when the activity spans a period
  title: string;
  roles: string;
  promoter?: string;
  url?: string;
};

export const service: Service[] = [
  {
    year: 2026,
    date: "2026-07-04",
    endDate: "2026-07-05",
    title: "第4回Science of Science 研究会",
    roles: "企画・運営 · 司会・パネリスト",
    promoter: "松井暉",
    url: "https://researchmap.jp/amrmap/academic_contribution/54325250",
  },
  {
    year: 2026,
    date: "2026-06-08",
    title: "人工知能学会全国大会（第40回） 若手交流ランチ会",
    roles: "企画・運営 · 司会・パネリスト",
    promoter: "松井暉",
    url: "https://researchmap.jp/amrmap/academic_contribution/53891868",
  },
  {
    year: 2026,
    date: "2026-06-08",
    title: "人工知能学会全国大会（第40回） 若手交流会：失敗談から学ぶ研究プロセス",
    roles: "企画・運営 · 司会・パネリスト",
    promoter: "松井暉",
    url: "https://researchmap.jp/amrmap/academic_contribution/53891864",
  },
  {
    year: 2025,
    date: "2025-12-08",
    title: "International Workshop on Conspiracy Theory and Misinfomation",
    roles: "企画・運営 · 司会・パネリスト",
    promoter: "Akira Matsui",
    url: "https://researchmap.jp/amrmap/academic_contribution/51857349",
  },
  {
    year: 2025,
    date: "2025-11-30",
    title: "ワークショップ「陰謀論とメディア報道」(主催・運営責任)",
    roles: "企画・運営",
    promoter: "松井暉",
    url: "https://researchmap.jp/amrmap/academic_contribution/51774373",
  },
  {
    year: 2022,
    date: "2022",
    endDate: "2024",
    title: "ウェブ・ソーシャルメディア 論文読み会",
    roles: "企画・運営",
    url: "https://researchmap.jp/amrmap/academic_contribution/50894325",
  },
];
