// AUTO-GENERATED by scripts/sync-researchmap.mjs.
// Source: https://researchmap.jp/amrmap (presentations).
// Do not edit manually except for fields preserved by the sync script
// (publications.highlight by DOI, grants.role by title, books.role by title).
// Run `node scripts/sync-researchmap.mjs` to regenerate.

export type Talk = {
  date: string; // YYYY-MM-DD
  title: string;
  venue: string;
  type: 'invited' | 'oral' | 'poster' | 'keynote';
  url?: string;
};

export const talks: Talk[] = [
  {
    date: "2026-05-22",
    type: "oral",
    title: "Wikipediaから見える 「言語ごとの知識のかたち」",
    venue: "文部科学省と国立大学附置研究所・センター 個別定例ランチミーティング 第150回神⼾⼤学計算社会科学研究センター",
    url: "https://researchmap.jp/amrmap/presentations/53773139",
  },
  {
    date: "2025-12-20",
    type: "invited",
    title: "Global Patterns of Knowledge: Language, Genre, and the Geography of Knowledge",
    venue: "CCSS Workshop on Computational SocialScience: Simulation + Data Science + Networks",
    url: "https://researchmap.jp/amrmap/presentations/51913323",
  },
  {
    date: "2025-12-14",
    type: "invited",
    title: "サイエンス・オブ・サイエンスで科学者の行動を分析する",
    venue: "第16回横幹連合コンファレンス",
    url: "https://researchmap.jp/amrmap/presentations/51857374",
  },
  {
    date: "2025-12-08",
    type: "invited",
    title: "Uncovering Knowledge Production Modes: Geopolitical Biases in Wikipedia's Fundamental Data",
    venue: "International Workshop on Conspiracy Theory and Misinformation",
    url: "https://researchmap.jp/amrmap/presentations/51857367",
  },
  {
    date: "2025-07-24",
    type: "poster",
    title: "Staying Streamed: The Impact of Loyalty and Diversity in Driving User Retention on Live Streaming Platforms",
    venue: "The International Conference for Computational Social Science",
    url: "https://researchmap.jp/amrmap/presentations/50693252",
  },
  {
    date: "2025-07-22",
    type: "oral",
    title: "Global Editing Patterns on Wikipedia Platform Reveal Segmentations in Knowledge Production",
    venue: "The International Conference for Computational Social Science",
    url: "https://researchmap.jp/amrmap/presentations/50693264",
  },
  {
    date: "2025-03-25",
    type: "invited",
    title: "ツイッター(X)以外の計算社会科学研究 情報通信と社会科学の学際領域「計算社会科学」の最前線",
    venue: "電子情報通信学会総合大会",
    url: "https://researchmap.jp/amrmap/presentations/49551637",
  },
  {
    date: "2025-03-11",
    type: "oral",
    title: "データドリブンな文章構造と情報伝達の抽出手法",
    venue: "言語処理学会 第31回年次大会",
    url: "https://researchmap.jp/amrmap/presentations/49399656",
  },
  {
    date: "2025-02-26",
    type: "poster",
    title: "TikTokにおける音楽的要素が拡散現象に与える影響の分析",
    venue: "第4回計算社会科学会大会(CSSJ2025)",
    url: "https://researchmap.jp/amrmap/presentations/49474898",
  },
  {
    date: "2025-02-19",
    type: "oral",
    title: "Wikipediaにおける編集パターンの言語間比較",
    venue: "第4回計算社会科学会大会(CSSJ2025)",
    url: "https://researchmap.jp/amrmap/presentations/49186092",
  },
  {
    date: "2025-02-18",
    type: "oral",
    title: "The impact of loyalty and diversity on user behavior in live streaming platform",
    venue: "第4回計算社会科学会大会(CSSJ2025)",
    url: "https://researchmap.jp/amrmap/presentations/49474879",
  },
  {
    date: "2025-02-16",
    type: "poster",
    title: "決済アプリの送金時のテキストメッセージ分析",
    venue: "第4回計算社会科学会大会(CSSJ2025)",
    url: "https://researchmap.jp/amrmap/presentations/49474901",
  },
  {
    date: "2024-11-07",
    type: "invited",
    title: "ライブ配信プラットフォームにおけるユーザー行動分析：探索・深化と感情体験",
    venue: "分析的マーケティング研究会セミナー",
    url: "https://researchmap.jp/amrmap/presentations/48405783",
  },
  {
    date: "2024-10-16",
    type: "invited",
    title: "Throw Your Hat in the Ring (of Wikipedia): Exploring Urban-Rural Disparities in Local Politicians' Information Supply",
    venue: "Wikimedia Research/Showcase",
    url: "https://researchmap.jp/amrmap/presentations/48245502",
  },
  {
    date: "2024-09-11",
    type: "invited",
    title: "ロイヤルティプログラムの分析：​努力の有無を考慮した報酬の効果",
    venue: "日本行動計量学会52回大会マーケティング特別セッション",
    url: "https://researchmap.jp/amrmap/presentations/47729939",
  },
  {
    date: "2024-09-09",
    type: "invited",
    title: "Wikipediaにおける情報供給に関する研究",
    venue: "学術情報メディアセンターセミナー「Web情報学の今」",
    url: "https://researchmap.jp/amrmap/presentations/47707610",
  },
  {
    date: "2024-07-19",
    type: "oral",
    title: "Balancing Act: The Dual Pathways of Exploitation and Exploration in Live Streaming",
    venue: "The International Conference for Computational Social Science",
    url: "https://researchmap.jp/amrmap/presentations/47182557",
  },
  {
    date: "2024-07-18",
    type: "poster",
    title: "Behind the screens of fandom: Unraveling the threads of online platform.",
    venue: "The International Conference for Computational Social Science",
    url: "https://researchmap.jp/amrmap/presentations/46790726",
  },
  {
    date: "2024-06-09",
    type: "oral",
    title: "購買行動とロイヤリティプログラム：努力の有無を考慮した報酬の効果の分析",
    venue: "日本マーケティング・サイエンス学会第115回研究大会",
    url: "https://researchmap.jp/amrmap/presentations/47371757",
  },
  {
    date: "2023-12-27",
    type: "oral",
    title: "The Two-Sided Nature of Online Platforms",
    venue: "CCSS Workshop on Computational Social Science",
    url: "https://researchmap.jp/amrmap/presentations/47498306",
  },
  {
    date: "2023-12-03",
    type: "oral",
    title: "家計簿データを利用したマイナポイントの効果測定",
    venue: "日本マーケティング・サイエンス学会第114回研究大会",
    url: "https://researchmap.jp/amrmap/presentations/47371736",
  },
  {
    date: "2023-07",
    type: "oral",
    title: "Exploring urban-rural disparities in the production of politicians’ information.",
    venue: "The International Conference for Computational Social Science",
    url: "https://researchmap.jp/amrmap/presentations/46790731",
  },
  {
    date: "2023",
    type: "oral",
    title: "Computational framework of ast model reveals mechanism of knowledge accumulation.",
    venue: "The International Conference for Computational Social Science",
    url: "https://researchmap.jp/amrmap/presentations/46790734",
  },
  {
    date: "2020-01-06",
    type: "oral",
    title: "Human behavior in collaborative work the case of peer-reviewing and forecasting.",
    venue: "CCSS Workshop on Computational Soci",
    url: "https://researchmap.jp/amrmap/presentations/47498316",
  },
  {
    date: "2020",
    type: "oral",
    title: "The impact of peer reviews on papers’ contribution potential.",
    venue: "The International Conference for Computational Social Science",
    url: "https://researchmap.jp/amrmap/presentations/46790741",
  },
  {
    date: "2020",
    type: "oral",
    title: "Leveraging clickstream trajectories to reveal low-quality workers in crowdsourced forecasting platforms.",
    venue: "The International Conference for Computational Social Science",
    url: "https://researchmap.jp/amrmap/presentations/46790739",
  },
  {
    date: "2018",
    type: "oral",
    title: "Playing under the influence (of twitch): The effects of streaming on gamers’ performance.",
    venue: "UCI Esports Conference,",
    url: "https://researchmap.jp/amrmap/presentations/46790744",
  },
];
